### PR TITLE
INTERNAL: vulkan/android: guard against unsupported AHB formats crashing

### LINKED ISSUE #702: Most games don't work
**Describe the bug**
I use the official Waydroid image of GApps LineageOS 18.1 and I installed libndk via waydroid-script. But most games I tried crash when I try to play them. It doesn't matter if I use libndk or libhoudini, as it acts the same. I tried it on my laptop with i5-8250U and UHD 620 and there were the same issues. Some games worked like Geometry Dash or Bad Piggies, but others like Angry Birds 2, Konosuba and Blue Archive did not.

**Screenshots**
Konosuba game not working

https://user-images.githubusercontent.com/97224849/213174973-20cde39d-3faf-4fd0-af66-f0815cf635b6.mp4

Blue Archive not working

https://user-images.githubusercontent.com/97224849/213175038-ab9e38b8-b10f-42e1-b608-b44ea9e78eb3.mp4

**General information (please complete the following information):**
 - Waydroid tools Version [e.g. 1.3.4]
 - Waydroid Images Version [lineage-18.1-20230107-GAPPS]

**Desktop (please complete the following information):**
 - OS: [Arch Linux x86_64]
 - GPU: [e.g. AMD Radeon™ RX 6700XT]
 - Kernel version: [6.1.6-zen1-1-zen]
 - Host mesa version: [mesa-git 23.0.0_devel]
 - Desktop: [Hyprland]

**Additional context**

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=radeon
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/GAPPS.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.3.4
ro.vndk.lite=true
waydroid.host.user=valorix
waydroid.host.uid=1000
waydroid.host.gid=1000
waydroid.xdg_runtime_dir=/run/user/1000
waydroid.pulse_runtime_path=/run/user/1000/pulse
waydroid.wayland_display=wayland-1
waydroid.stub_sensors_hal=1
 - Output of `waydroid log`
 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services

### LINKED ISSUE #2187: [BUG] Intel gpu causes crash of waydroid
### Describe the bug

when i run it it pops up a black screen then just crash, i need to use software rendering when i want to use it but i want hardware acceleration

### Waydroid version

1.6.0

### Device

Linux Desktop

### Operating System

Nobara Linux 43

### Kernel version

6.18.2-200.nobara.fc43.x86_64

### Desktop Environment

GNOME 49

### GPU

Nvidia RTX 5060 (dgpu) Intel Raptor Lake-S UHD Graphics (thats what linux tells me)

### Logs

[waydroid-bugreport.tar.xz.gz](https://github.com/user-attachments/files/24546347/waydroid-bugreport.tar.xz.gz)

### PR DESCRIPTION
**Pull request by uzairdeveloper223**
### Problem

`vk_ahb_format_to_image_format()` returns `VK_FORMAT_UNDEFINED` for AHB formats not in the equivalence table (such as ETC2/EAC compressed formats). When this happens, `get_ahb_buffer_format_properties2()` falls into the external format path and calls `AHardwareBuffer_getNativeHandle()`, which can return a null handle when gralloc cannot process the format. This leads to a SIGABRT.

There is a secondary crash site in `vk_common_GetAndroidHardwareBufferPropertiesANDROID` where the native handle is used with an assert that aborts on null.

### Changes

Added defensive null-check guards at both `AHardwareBuffer_getNativeHandle` call sites:

1. In `get_ahb_buffer_format_properties2()`: check if the native handle is null before passing it to `u_gralloc_get_buffer_basic_info()`. Return `VK_ERROR_FORMAT_NOT_SUPPORTED`.

2. In `vk_common_GetAndroidHardwareBufferPropertiesANDROID`: replace the assert with a proper null check. Return `VK_ERROR_FORMAT_NOT_SUPPORTED`.

Both error paths log the AHB format code via `mesa_loge` to aid debugging.

### Context

This crash is triggered in Waydroid when ARM64 Unity games attempt to use ETC2 compressed textures through AHardwareBuffer on Intel GPUs (Mesa ANV). Originally, a companion Vulkan layer workaround was proposed in waydroid/android_hardware_waydroid#69, but addressing the root cause here in Mesa ensures that unsupported AHB formats fail gracefully instead of crashing the application.

### Testing

Tested on Intel UHD 620 with Waydroid LineageOS 20. ARM64 Unity games that previously crashed with SIGABRT on launch now receive `VK_ERROR_FORMAT_NOT_SUPPORTED` and successfully fall back to uncompressed textures.

Closes: https://github.com/waydroid/waydroid/issues/702
Closes: https://github.com/waydroid/waydroid/issues/2187

Signed-off-by: Uzair Mughal <contact@uzair.is-a.dev>

### CODE REVIEW

**Comment by aleasto** [comment]
I must say this seems weird to me. But I'm not opposed to merging it. Could you add a reference to the upstream merge request in the commit message?

**Comment by uzairdeveloper223** [comment]
> I must say this seems weird to me. But I'm not opposed to merging it. Could you add a reference to the upstream merge request in the commit message?

This patch isn't really upstream-submittable, the crash only happens in Waydroid's environment where ARM64 apps hit gralloc_gbm with ETC2 AHB formats via libndk/libhoudini translation. On real Android devices with vendor gralloc, these formats either work natively or never get allocated as AHardwareBuffers in the first place, so upstream Mesa would likely reject it as a Waydroid-specific edge case.
That's why I prefixed the commit with INTERNAL:. The null-check guards are defensive and don't change behavior for any format that actually works through gralloc, they just prevent the SIGABRT for formats that were never going to succeed anyway. Without this, users hitting [#702](https://github.com/waydroid/waydroid/issues/702) and [#2187](https://github.com/waydroid/waydroid/issues/2187) have no fix on the Mesa side.
Happy to adjust the commit message if you want different wording, but there isn't an upstream MR to reference.

File: src/vulkan/runtime/vk_android.c [hunk 1]
```diff
@@ -951,9 +964,15 @@ vk_common_GetAndroidHardwareBufferPropertiesANDROID(
...
-   pProperties->allocationSize = lseek(handle->data[0], 0, SEEK_END);
+    const native_handle_t *handle = AHardwareBuffer_getNativeHandle(buffer);
+    if (!handle || handle->numFds <= 0) {
+       AHardwareBuffer_Desc desc;
+       AHardwareBuffer_describe(buffer, &desc);
+       mesa_loge("AHardwareBuffer has invalid native handle (format 0x%x)",
+                 desc.format);
+       return VK_ERROR_FORMAT_NOT_SUPPORTED;
+    }
+    pProperties->allocationSize = lseek(handle->data[0], 0, SEEK_END);
```
Comment (aleasto) [inline src/vulkan/runtime/vk_android.c]: nit: your indentation is off

**Comment by aleasto** [comment]
Please squash the commits, and add:
```
Closes: https://github.com/waydroid/waydroid/issues/702
Closes: https://github.com/waydroid/waydroid/issues/2187
```
to the commit message

**Comment by uzairdeveloper223** [comment]
@aleasto I've fixed the indentation styling! My local git environment got corrupted so I can't easily download the repo and squash these commits locally right now.

Could you please just use the "Squash and merge" button on your end and paste in the issue links? Thanks!

Commit message copy-paste: `INTERNAL: vulkan/android: guard against unsupported AHB formats crashing`

```markdown
vk_ahb_format_to_image_format() returns VK_FORMAT_UNDEFINED for AHB
formats not in the equivalence table (such as ETC2/EAC compressed
formats). When this happens, get_ahb_buffer_format_properties2() falls
into the external format path and calls AHardwareBuffer_getNativeHandle(),
which can return a null handle when gralloc cannot process the format.
This leads to a SIGABRT.
There is a secondary crash site in
vk_common_GetAndroidHardwareBufferPropertiesANDROID where the native
handle is used with an assert that aborts on null.
Added null-check guards at both AHardwareBuffer_getNativeHandle call
sites to return VK_ERROR_FORMAT_NOT_SUPPORTED instead of crashing.
Closes: https://github.com/waydroid/waydroid/issues/702
Closes: https://github.com/waydroid/waydroid/issues/2187
```

**Comment by uzairdeveloper223** [comment]
@aleasto also close this because the issue was resolved 

waydroid/waydroid#2259

**Comment by hmtheboy154** [comment]
I don't think this should have `INTERNAL:` tag
that tag was there because we cherry-picked some patches from Project Celadon

**Comment by uzairdeveloper223** [comment]
> I don't think this should have `INTERNAL:` tag that tag was there because we cherry-picked some patches from Project Celadon

Ah, my bad! I prefixed it with `INTERNAL:` to indicate that this is a Waydroid-specific workaround (since the crash happens when unity ARM games/apps run under our translation environments like `libndk` and `libhoudini`), and it's not a generic patch meant to be sent upstream to the freedesktop.org Mesa repo.
I didn't realize the `INTERNAL:` prefix was historically reserved strictly for Project Celadon cherry-picks in this repository. Good to know for next time!
